name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      llvm_version: 19.1.0

    steps:
      - uses: actions/checkout@v2

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Checkout llvm
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          ref: "llvmorg-${{ env.llvm_version }}"
          path: "llvm"

      - name: Build llvm
        run: |
          mkdir build
          mkdir install
          cmake `
            -S ".\llvm\llvm" `
            -B ".\build" `
            -G "Visual Studio 17 2022" `
            -Thost=x64 `
            -A x64 `
            -DLLVM_ENABLE_PROJECTS="lld;clang" `
            -DCMAKE_BUILD_TYPE=Release `
            -DLLVM_ENABLE_LIBXML2=OFF `
            -DLLVM_ENABLE_ZLIB=OFF `
            -DCMAKE_INSTALL_PREFIX=".\install"
          cmake --build .\build --target INSTALL --config Release -j
          7z a -mx9 "LLVM-${{ env.llvm_version }}-win64.7z" ".\install\*"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LLVM-${{ env.llvm_version }}-win64
          path: LLVM-${{ env.llvm_version }}-win64.7z
