name: Build and Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [trigger-build]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      llvm_version: 19.1.0

    steps:
      - uses: actions/checkout@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Checkout llvm
        uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: "llvmorg-${{ env.llvm_version }}"
          path: "llvm"

      - name: Build llvm
        run: |
          mkdir build
          mkdir install
          cmake `
            -S ".\llvm\llvm" `
            -B ".\build" `
            -G "Visual Studio 17 2022" `
            -Thost=x64 `
            -A x64 `
            -DLLVM_ENABLE_PROJECTS="lld;clang" `
            -DCMAKE_BUILD_TYPE=Release `
            -DLLVM_ENABLE_LIBXML2=OFF `
            -DLLVM_ENABLE_ZLIB=OFF `
            -DCMAKE_INSTALL_PREFIX=".\install"
          cmake --build .\build --target INSTALL --config Release -j
          7z a -mx9 "LLVM-${{ env.llvm_version }}-win64.7z" ".\install\*"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LLVM-${{ env.llvm_version }}-win64
          path: LLVM-${{ env.llvm_version }}-win64.7z

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.llvm_version }}
          name: LLVM-${{ env.llvm_version }}-win64
          body: |
            LLVM ${{ env.llvm_version }}, built to be compatible and sufficient for development using the Rust library [inkwell](https://crates.io/crates/inkwell) on Windows.
            Requires [Visual Studio 2022](https://visualstudio.microsoft.com/vs/community/) with the "Desktop development with C++" workload installed on the Windows computer to enable usage of this LLVM build.
            Requires [7-zip](https://www.7-zip.org/download.html) to unpack.
          files: LLVM-${{ env.llvm_version }}-win64.7z
          draft: false
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
